In [15]:
import pandas as pd
import numpy as np

df = pd.read_csv("Latest Covid-19 India Status.csv")
display(df)

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Death Ratio,Population
0,Andaman and Nicobar,10766,0,10637,129,0.00,98.80,1.20,100896618
1,Andhra Pradesh,2340676,0,2325943,14733,0.00,99.37,0.63,128500364
2,Arunachal Pradesh,67049,0,66753,296,0.00,99.56,0.44,658019
3,Assam,746159,5,738119,8035,0.00,98.92,1.08,290492
4,Bihar,855267,1,842952,12314,0.00,98.56,1.44,40100376
5,Chandigarh,100693,0,99508,1185,0.00,98.82,1.18,30501026
6,Chhattisgarh,1187695,0,1173505,14190,0.00,98.81,1.19,28900667
7,Dadra and Nagar Haveli and Daman and Diu,11592,0,11588,4,0.00,99.97,0.03,231502578
8,Delhi,2040910,14,2014230,26666,0.00,98.69,1.31,773997
9,Goa,263346,3,259329,4014,0.00,98.47,1.52,3772103
10,Gujarat,1291383,5,1280299,11079,0.00,99.14,0.86,70400153
11,Haryana,1078903,27,1068121,10755,0.00,99.00,1.00,7503010
12,Himachal Pradesh,322905,4,318660,4241,0.00,98.69,1.31,3436948
13,Jammu and Kashmir,482023,0,477231,4792,0.00,99.01,0.99,66001
14,Jharkhand,443826,1,438491,5334,0.00,98.80,1.20,124904071
15,Karnataka,4088769,12,4048399,40358,0.00,99.01,0.99,1711947
16,Kerala,6907241,18,6835181,72042,0.00,98.96,1.04,91702478
17,Ladakh,29602,0,29371,231,0.00,99.22,0.78,4184959
18,Lakshadweep,11415,0,11363,52,0.00,99.54,0.46,11700099
19,Madhya Pradesh,1056351,0,1045565,10786,0.00,98.98,1.02,14999397
20,Maharashtra,8171048,214,8022276,148558,0.00,98.18,1.82,399001
21,Manipur,140034,0,137885,2149,0.00,98.47,1.53,47099270
22,Meghalaya,96983,3,95352,1628,0.00,98.32,1.68,79502477
23,Mizoram,239560,1,238825,734,0.00,99.69,0.31,1308967
24,Nagaland,36033,0,35251,782,0.00,97.83,2.17,38157311
25,Odisha,1348409,59,1339135,9215,0.00,99.31,0.68,19301096
26,Puducherry,177547,0,175566,1981,0.00,98.88,1.12,2073074
27,Punjab,793644,1233,773073,19338,0.16,97.41,2.44,34698876
28,Rajasthan,1326465,2,1316727,9736,0.00,99.27,0.73,1521992
29,Sikkim,44927,4,44422,501,0.01,98.88,1.12,83697770
30,Tamil Nadu,3610655,5,3572569,38081,0.00,98.95,1.05,35998752
31,Telengana,844432,8,840313,4111,0.00,99.51,0.49,69599762
32,Tripura,108493,1,107550,942,0.00,99.13,0.87,1646050
33,Uttar Pradesh,2145431,57,2121662,23712,0.00,98.89,1.11,1158040
34,Uttarakhand,452571,0,444803,7768,0.00,98.28,1.72,85002417
35,West Bengal,2126282,135,2104592,21555,0.01,98.98,1.01,32199722

In [7]:
#print(df.isnull().sum())

print(df.info())

print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   State/UTs        36 non-null     str
 1   Total Cases      36 non-null     int64
 2   Active           36 non-null     int64
 3   Discharged       36 non-null     int64
 4   Deaths           36 non-null     int64
 5   Active Ratio     36 non-null     float64
 6   Discharge Ratio  36 non-null     float64
 7   Death Ratio      36 non-null     float64
 8   Population       36 non-null     int64
dtypes: float64(3), int64(5), str(1)
memory usage: 2.7 KB
None
        Total Cases       Active    Discharged         Deaths  Active Ratio  \
count  3.600000e+01    36.000000  3.600000e+01      36.000000     36.000000
mean   1.249975e+06    50.333333  1.235146e+06   14778.527778      0.005000
std    1.846038e+06   207.118048  1.820328e+06   27221.140636      0.026673
min    1.076600e+04     0.000000  1.063700e+04       4.000000      0.000000
25%    1.065430e+05     0.000000  1.055395e+05    1124.250000      0.000000
50%    6.140910e+05     1.500000  6.076750e+05    6551.000000      0.000000
75%    1.331951e+06     9.000000  1.322329e+06   14325.750000      0.000000
max    8.171048e+06  1233.000000  8.022276e+06  148558.000000      0.160000

       Discharge Ratio  Death Ratio    Population
count        36.000000    36.000000  3.600000e+01
mean         98.897222     1.097778  3.971861e+07
std           0.506854     0.494791  5.050913e+07
min          97.410000     0.030000  6.600100e+04
25%          98.690000     0.840000  1.695473e+06
50%          98.935000     1.065000  2.410088e+07
75%          99.160000     1.310000  6.979986e+07
max          99.970000     2.440000  2.315026e+08

In [17]:
# loc: label-based selection
display(df.loc[0:2,["State/UTs","Total Cases","Discharged","Deaths"]])

# iloc: position-based selection
display(df.iloc[0:3,0:3])

display(df[df["State/UTs"] == "Maharashtra"])

             State/UTs  Total Cases  Discharged  Deaths
0  Andaman and Nicobar        10766       10637     129
1       Andhra Pradesh      2340676     2325943   14733
2    Arunachal Pradesh        67049       66753     296

             State/UTs  Total Cases  Active
0  Andaman and Nicobar        10766       0
1       Andhra Pradesh      2340676       0
2    Arunachal Pradesh        67049       0

,State/UTs,Total Cases,Active,Discharged,Deaths,Active Ratio,Discharge Ratio,Death Ratio,Population
20,Maharashtra,8171048,214,8022276,148558,0.0,98.18,1.82,399001

In [42]:
from tabulate import tabulate
table = tabulate(df,headers="keys",tablefmt="grid",colalign=("left","left","right"),maxcolwidths=[None, 30])
print(table)

+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
|    | State/UTs                  |   Total Cases |   Active |   Discharged |   Deaths |   Active Ratio |   Discharge Ratio |   Death Ratio |   Population |
+====+============================+===============+==========+==============+==========+================+===================+===============+==============+
| 0  | Andaman and Nicobar        |         10766 |        0 |        10637 |      129 |           0    |             98.8  |          1.2  |    100896618 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 1  | Andhra Pradesh             |       2340676 |        0 |      2325943 |    14733 |           0    |             99.37 |          0.63 |    128500364 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 2  | Arunachal Pradesh          |         67049 |        0 |        66753 |      296 |           0    |             99.56 |          0.44 |       658019 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 3  | Assam                      |        746159 |        5 |       738119 |     8035 |           0    |             98.92 |          1.08 |       290492 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 4  | Bihar                      |        855267 |        1 |       842952 |    12314 |           0    |             98.56 |          1.44 |     40100376 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 5  | Chandigarh                 |        100693 |        0 |        99508 |     1185 |           0    |             98.82 |          1.18 |     30501026 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 6  | Chhattisgarh               |       1187695 |        0 |      1173505 |    14190 |           0    |             98.81 |          1.19 |     28900667 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 7  | Dadra and Nagar Haveli and |         11592 |        0 |        11588 |        4 |           0    |             99.97 |          0.03 |    231502578 |
|    | Daman and Diu              |               |          |              |          |                |                   |               |              |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 8  | Delhi                      |       2040910 |       14 |      2014230 |    26666 |           0    |             98.69 |          1.31 |       773997 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 9  | Goa                        |        263346 |        3 |       259329 |     4014 |           0    |             98.47 |          1.52 |      3772103 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 10 | Gujarat                    |       1291383 |        5 |      1280299 |    11079 |           0    |             99.14 |          0.86 |     70400153 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 11 | Haryana                    |       1078903 |       27 |      1068121 |    10755 |           0    |             99    |          1    |      7503010 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 12 | Himachal Pradesh           |        322905 |        4 |       318660 |     4241 |           0    |             98.69 |          1.31 |      3436948 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 13 | Jammu and Kashmir          |        482023 |        0 |       477231 |     4792 |           0    |             99.01 |          0.99 |        66001 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 14 | Jharkhand                  |        443826 |        1 |       438491 |     5334 |           0    |             98.8  |          1.2  |    124904071 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 15 | Karnataka                  |       4088769 |       12 |      4048399 |    40358 |           0    |             99.01 |          0.99 |      1711947 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 16 | Kerala                     |       6907241 |       18 |      6835181 |    72042 |           0    |             98.96 |          1.04 |     91702478 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 17 | Ladakh                     |         29602 |        0 |        29371 |      231 |           0    |             99.22 |          0.78 |      4184959 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 18 | Lakshadweep                |         11415 |        0 |        11363 |       52 |           0    |             99.54 |          0.46 |     11700099 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 19 | Madhya Pradesh             |       1056351 |        0 |      1045565 |    10786 |           0    |             98.98 |          1.02 |     14999397 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 20 | Maharashtra                |       8171048 |      214 |      8022276 |   148558 |           0    |             98.18 |          1.82 |       399001 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 21 | Manipur                    |        140034 |        0 |       137885 |     2149 |           0    |             98.47 |          1.53 |     47099270 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 22 | Meghalaya                  |         96983 |        3 |        95352 |     1628 |           0    |             98.32 |          1.68 |     79502477 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 23 | Mizoram                    |        239560 |        1 |       238825 |      734 |           0    |             99.69 |          0.31 |      1308967 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 24 | Nagaland                   |         36033 |        0 |        35251 |      782 |           0    |             97.83 |          2.17 |     38157311 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 25 | Odisha                     |       1348409 |       59 |      1339135 |     9215 |           0    |             99.31 |          0.68 |     19301096 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 26 | Puducherry                 |        177547 |        0 |       175566 |     1981 |           0    |             98.88 |          1.12 |      2073074 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 27 | Punjab                     |        793644 |     1233 |       773073 |    19338 |           0.16 |             97.41 |          2.44 |     34698876 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 28 | Rajasthan                  |       1326465 |        2 |      1316727 |     9736 |           0    |             99.27 |          0.73 |      1521992 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 29 | Sikkim                     |         44927 |        4 |        44422 |      501 |           0.01 |             98.88 |          1.12 |     83697770 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 30 | Tamil Nadu                 |       3610655 |        5 |      3572569 |    38081 |           0    |             98.95 |          1.05 |     35998752 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 31 | Telengana                  |        844432 |        8 |       840313 |     4111 |           0    |             99.51 |          0.49 |     69599762 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 32 | Tripura                    |        108493 |        1 |       107550 |      942 |           0    |             99.13 |          0.87 |      1646050 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 33 | Uttar Pradesh              |       2145431 |       57 |      2121662 |    23712 |           0    |             98.89 |          1.11 |      1158040 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 34 | Uttarakhand                |        452571 |        0 |       444803 |     7768 |           0    |             98.28 |          1.72 |     85002417 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+
| 35 | West Bengal                |       2126282 |      135 |      2104592 |    21555 |           0.01 |             98.98 |          1.01 |     32199722 |
+----+----------------------------+---------------+----------+--------------+----------+----------------+-------------------+---------------+--------------+

part c

In [1]:
import pandas as pd
import numpy as np

# Sample sales dataset 
data = {
    "OrderID": range(1, 11),
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "Dave", "Bob", "Eve", "Charlie", "Alice", "Dave"],
    "Region": ["East", "West", "East", "East", "South", "West", "North", "East", "West", "South"],
    "Product": ["Widget", "Gadget", "Widget", "Gizmo", "Widget", "Gadget", "Gizmo", "Gadget", "Widget", "Gizmo"],
    "Quantity": [10, 5, 8, 3, np.nan, 7, 12, 4, 6, 9],
    "Price": [2.5, 15.0, 2.5, 7.0, 2.5, 15.0, 7.0, 15.0, 2.5, 7.0],
}
df = pd.DataFrame(data)
df

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

In [2]:
s = pd.Series([100, 200, 300, 400], index=["a", "b", "c", "d"], name="Sales")
print(s)
print("\nType:", type(s))
print("Value at label 'b':", s["b"])

a    100
b    200
c    300
d    400
Name: Sales, dtype: int64

Type: <class 'pandas.Series'>
Value at label 'b': 200

In [3]:
# Total quantity sold per region
print("Sum of Quantity by Region:")
display(df.groupby("Region")["Quantity"].sum())

# Average price per product
print("\nMean Price by Product:")
display(df.groupby("Product")["Price"].mean())

# Multiple aggregations at once with agg()
print("\nMultiple aggregations with agg():")
display(df.groupby("Region").agg(
    total_qty=("Quantity", "sum"),
    avg_price=("Price", "mean"),
    order_count=("OrderID", "count")
))

Sum of Quantity by Region:

Region
East     25.0
North    12.0
South     9.0
West     18.0
Name: Quantity, dtype: float64

Mean Price by Product:

Product
Gadget    15.0
Gizmo      7.0
Widget     2.5
Name: Price, dtype: float64

Multiple aggregations with agg():

        total_qty  avg_price  order_count
Region
East         25.0   6.750000            4
North        12.0   7.000000            1
South         9.0   4.750000            2
West         18.0  10.833333            3

In [4]:
pivot = pd.pivot_table(
    df,
    values="Quantity",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)
pivot

Product  Gadget  Gizmo  Widget
Region
East        4.0    3.0    18.0
North       0.0   12.0     0.0
South       0.0    9.0     0.0
West       12.0    0.0     6.0

In [5]:
print("Missing values per column:")
display(df.isnull().sum())

print("\nRows with any missing values:")
display(df[df.isnull().any(axis=1)])

print("\nDropping rows with missing values (dropna):")
display(df.dropna())

print("\nFilling missing Quantity with the column mean (fillna):")
df_filled = df.copy()
df_filled["Quantity"] = df_filled["Quantity"].fillna(df_filled["Quantity"].mean())
display(df_filled)

Missing values per column:

OrderID     0
Customer    0
Region      0
Product     0
Quantity    1
Price       0
dtype: int64

Rows with any missing values:

   OrderID Customer Region Product  Quantity  Price
4        5     Dave  South  Widget       NaN    2.5

Dropping rows with missing values (dropna):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Filling missing Quantity with the column mean (fillna):

   OrderID Customer Region Product   Quantity  Price
0        1    Alice   East  Widget  10.000000    2.5
1        2      Bob   West  Gadget   5.000000   15.0
2        3  Charlie   East  Widget   8.000000    2.5
3        4    Alice   East   Gizmo   3.000000    7.0
4        5     Dave  South  Widget   7.111111    2.5
5        6      Bob   West  Gadget   7.000000   15.0
6        7      Eve  North   Gizmo  12.000000    7.0
7        8  Charlie   East  Gadget   4.000000   15.0
8        9    Alice   West  Widget   6.000000    2.5
9       10     Dave  South   Gizmo   9.000000    7.0

In [6]:
df_t = df_filled.copy()

# apply(): create a new column using a custom function
df_t["Total"] = df_t.apply(lambda row: row["Quantity"] * row["Price"], axis=1)

# map(): map values in a column to new values
region_codes = {"East": "E", "West": "W", "South": "S", "North": "N"}
df_t["RegionCode"] = df_t["Region"].map(region_codes)

# astype(): change a column's data type
df_t["Quantity"] = df_t["Quantity"].astype(int)

# rename(): rename columns
df_t = df_t.rename(columns={"Total": "TotalRevenue"})

# sort_values(): sort rows by a column
df_t = df_t.sort_values(by="TotalRevenue", ascending=False)

df_t

   OrderID Customer Region Product  Quantity  Price  TotalRevenue RegionCode
5        6      Bob   West  Gadget         7   15.0    105.000000          W
6        7      Eve  North   Gizmo        12    7.0     84.000000          N
1        2      Bob   West  Gadget         5   15.0     75.000000          W
9       10     Dave  South   Gizmo         9    7.0     63.000000          S
7        8  Charlie   East  Gadget         4   15.0     60.000000          E
0        1    Alice   East  Widget        10    2.5     25.000000          E
3        4    Alice   East   Gizmo         3    7.0     21.000000          E
2        3  Charlie   East  Widget         8    2.5     20.000000          E
4        5     Dave  South  Widget         7    2.5     17.777778          S
8        9    Alice   West  Widget         6    2.5     15.000000          W

In [7]:
# A second DataFrame with extra customer info, to merge with df
customer_info = pd.DataFrame({
    "Customer": ["Alice", "Bob", "Charlie", "Dave", "Eve"],
    "City": ["New York", "Chicago", "Boston", "Houston", "Miami"],
    "MembershipLevel": ["Gold", "Silver", "Gold", "Bronze", "Silver"]
})

# merge(): SQL-style join on a common column
merged_df = pd.merge(df, customer_info, on="Customer", how="left")
print("merge() result:")
display(merged_df.head())

# join(): join on index (set Customer as index on both first)
joined_df = df.set_index("Customer").join(customer_info.set_index("Customer"), how="left")
print("\njoin() result:")
display(joined_df.head())

# concat(): stack DataFrames together (e.g., two batches of orders)
batch1 = df.iloc[:5]
batch2 = df.iloc[5:]
concatenated_df = pd.concat([batch1, batch2], ignore_index=True)
print("\nconcat() result (recombined batches):")
display(concatenated_df)

merge() result:

   OrderID Customer Region Product  Quantity  Price      City MembershipLevel
0        1    Alice   East  Widget      10.0    2.5  New York            Gold
1        2      Bob   West  Gadget       5.0   15.0   Chicago          Silver
2        3  Charlie   East  Widget       8.0    2.5    Boston            Gold
3        4    Alice   East   Gizmo       3.0    7.0  New York            Gold
4        5     Dave  South  Widget       NaN    2.5   Houston          Bronze

join() result:

          OrderID Region Product  Quantity  Price      City MembershipLevel
Customer
Alice           1   East  Widget      10.0    2.5  New York            Gold
Bob             2   West  Gadget       5.0   15.0   Chicago          Silver
Charlie         3   East  Widget       8.0    2.5    Boston            Gold
Alice           4   East   Gizmo       3.0    7.0  New York            Gold
Dave            5  South  Widget       NaN    2.5   Houston          Bronze

concat() result (recombined batches):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0